# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('geonameid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('feature_code', models.CharField(max_length=15)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('population', models.IntegerField()),
            ],
            options={
                'ordering': ('name', 'country_code'),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('legal_name', models.CharField(blank=True, max_length=100)),
                ('cif', models.CharField(blank=True, max_length=25)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(choices=[('internet', 'Internet'), ('gaming', 'Gaming'), ('other', 'Other')], max_length=15)),
                ('country', models.CharField(choices=[('es', 'ES')], max_length=2)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('is_canonical_company', models.BooleanField(default=True, help_text='Official company, in case of duplicates')),
                ('fee', models.CharField(blank=True, max_length=25)),
                ('nubelo_id', models.IntegerField(blank=True)),
                ('nubelo_url', models.URLField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('n/a', 'N/A'), ('contacted', 'Contacted'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='n/a', max_length=15)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='crm.City')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='CompanyNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('phone_call', 'Phone call'), ('meeting', 'Meeting'), ('email', 'Email'), ('proposal_sent', 'Proposal Sent'), ('proposal_signed', 'Proposal Signed'), ('blind_cv', 'Blind CV'), ('other', 'Other')], max_length=15)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('blind_cvs_sent', models.IntegerField(default=0)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('document', models.FileField(blank=True, upload_to='uploads/notes/companies/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_notes', to='crm.Company')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('mobile', models.CharField(blank=True, max_length=25)),
                ('country', models.CharField(max_length=2)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.Company')),
            ],
            options={
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('description', models.TextField()),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('num_vacancies', models.IntegerField(default=1)),
                ('job_type', models.CharField(choices=[('freelance', 'Freelance'), ('employee', 'Employee')], max_length=15)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.CharField(blank=True, max_length=25)),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('document', models.FileField(blank=True, upload_to='uploads/docs/process/%Y/%m/%d/')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='crm.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='crm.Company')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='ProcessNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('candidates_sent', 'Candidates Sent'), ('client_interviewed_candidate', 'Client Interviewed Candidate'), ('client_made_job_offer', 'Client Made Job Offer'), ('candidate_accepted_offer', 'Candidate Accepted Offer'), ('candidate_rejected_offer', 'Candidate Rejected Offer'), ('other', 'Other')], max_length=25)),
                ('action_num_candidates', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('document', models.FileField(blank=True, upload_to='uploads/notes/process/%Y/%m/%d/')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_notes', to='crm.Process')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=31)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='process',
            name='skills',
            field=models.ManyToManyField(related_name='processes', to='crm.Skill'),
        ),
        migrations.AddField(
            model_name='company',
            name='skills',
            field=models.ManyToManyField(related_name='companies', to='crm.Skill'),
        ),
    ]
