# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='nubelo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
