# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name', 'country'), 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'industries'},
        ),
        migrations.AddField(
            model_name='job',
            name='nubelo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='nubelo_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
