# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20160617_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
    ]
