# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20160515_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-timestamp',), 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='process',
            name='total_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
