# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_company_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='country',
        ),
        migrations.AlterField(
            model_name='company',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
