# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20160516_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='job_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('freelance', 'Freelance')], max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([('slug', 'company')]),
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together=set([('slug', 'company')]),
        ),
    ]
