# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_slug_company_unique_together_contact_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('n/a', 'N/A'), ('contacted', 'Contacted'), ('accepted', 'Accepted'), ('declined', 'Declined')], max_length=15),
        ),
    ]
