# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20160618_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaction',
            name='title',
        ),
        migrations.AddField(
            model_name='companyaction',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('done', 'Done')], default='to_do', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyaction',
            name='action',
            field=models.CharField(choices=[('phone_call', 'Phone call'), ('meeting', 'Meeting'), ('email', 'Email'), ('proposal_sent', 'Proposal Sent'), ('proposal_signed', 'Proposal Signed'), ('blind_cv', 'Blind CV'), ('other', 'Other')], max_length=25),
        ),
    ]
