# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20160525_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('is_primary_contact',)},
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('n/a', 'N/A')], max_length=15),
        ),
    ]
