# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20160525_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-is_primary_contact',)},
        ),
    ]
