# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20160525_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-processes',), 'verbose_name_plural': 'companies'},
        ),
    ]
