# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20160621_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaction',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='to_do', max_length=25),
        ),
    ]
