# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_companyaction_completed_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaction',
            name='completed_timestamp',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
